"use strict";

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert(
      "role",
      [
        {
          role_id: 1,
          role_name: "Student",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          role_id: 2,
          role_name: "Instructor",
          created_at: new Date(),
          updated_at: new Date(),
        },
      ],
      {}
    );

    await queryInterface.bulkInsert(
      "authentication",
      [
        {
          user_id: "EmGdTPFbxBDuBO2F1n-u7",
          email: "test@test.com",
          password_hash:
            "$2b$10$1Dwcfq0NiLy3uUc7lcb7kOc.6PVtcXo3NGXDMFxplP8nifMG3/jo6",
          role_id: 1,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          user_id: "G42NJ4jlvRNdHbi0b5ROE",
          email: "test2@test.com",
          password_hash:
            "$2b$10$v0yaaBeupS6J65GiWBSZPehR2yMjZ12n0ONTkgjnwi7YrliUVi6K.",
          role_id: 2,
          created_at: new Date(),
          updated_at: new Date(),
        },
      ],
      {}
    );

    await queryInterface.bulkInsert(
      "customer_info",
      [
        {
          user_id: "EmGdTPFbxBDuBO2F1n-u7",
          email: "test@test.com",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          user_id: "G42NJ4jlvRNdHbi0b5ROE",
          email: "test2@test.com",
          created_at: new Date(),
          updated_at: new Date(),
        },
      ],
      {}
    );

    var curDate = new Date();
    curDate.setDate(curDate.getDate() + 30);
    await queryInterface.bulkInsert(
      "course",
      [
        {
          user_id: "G42NJ4jlvRNdHbi0b5ROE",
          title: "Yo",
          description: "Yo",
          image_url: "https://ik.imgkit.net/ikmedia/logo/light_T4buIzohVH.svg",
          category: "category",
          subject: "subject",
          enrolled: 20,
          started_at: new Date(),
          ended_at: curDate,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          user_id: "G42NJ4jlvRNdHbi0b5ROE",
          title: "Hello",
          description: "Hello",
          image_url: "https://ik.imgkit.net/ikmedia/logo/light_T4buIzohVH.svg",
          category: "category",
          subject: "subject",
          enrolled: 19,
          started_at: new Date(),
          ended_at: curDate,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          user_id: "G42NJ4jlvRNdHbi0b5ROE",
          title: "Arthur",
          description: "Arthur",
          image_url: "https://ik.imgkit.net/ikmedia/logo/light_T4buIzohVH.svg",
          category: "category",
          subject: "subject",
          enrolled: 18,
          started_at: new Date(),
          ended_at: curDate,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          user_id: "G42NJ4jlvRNdHbi0b5ROE",
          title: "ลองภาษาไทยบ้าง",
          description: "description",
          image_url: "https://ik.imgkit.net/ikmedia/logo/light_T4buIzohVH.svg",
          category: "category",
          subject: "subject",
          enrolled: 17,
          started_at: new Date(),
          ended_at: curDate,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          user_id: "G42NJ4jlvRNdHbi0b5ROE",
          title: "โอเคเปลี่ยนคำ",
          description: "description",
          image_url: "https://ik.imgkit.net/ikmedia/logo/light_T4buIzohVH.svg",
          category: "category",
          subject: "subject",
          enrolled: 16,
          started_at: new Date(),
          ended_at: curDate,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          user_id: "G42NJ4jlvRNdHbi0b5ROE",
          title: "ฉันหนาววว",
          description: "description",
          image_url: "https://ik.imgkit.net/ikmedia/logo/light_T4buIzohVH.svg",
          category: "category",
          subject: "subject",
          enrolled: 15,
          started_at: new Date(),
          ended_at: curDate,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          user_id: "G42NJ4jlvRNdHbi0b5ROE",
          title: "A bit in english",
          description: "description",
          image_url: "https://ik.imgkit.net/ikmedia/logo/light_T4buIzohVH.svg",
          category: "category",
          subject: "subject",
          enrolled: 14,
          started_at: new Date(),
          ended_at: curDate,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          user_id: "G42NJ4jlvRNdHbi0b5ROE",
          title: "Python for everyone",
          description: "description",
          image_url: "https://ik.imgkit.net/ikmedia/logo/light_T4buIzohVH.svg",
          category: "category",
          subject: "subject",
          enrolled: 13,
          started_at: new Date(),
          ended_at: curDate,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          user_id: "G42NJ4jlvRNdHbi0b5ROE",
          title: "Node.js for someone",
          description: "description",
          image_url: "https://ik.imgkit.net/ikmedia/logo/light_T4buIzohVH.svg",
          category: "category",
          subject: "subject",
          enrolled: 12,
          started_at: new Date(),
          ended_at: curDate,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          user_id: "G42NJ4jlvRNdHbi0b5ROE",
          title: "Teach me please",
          description: "description",
          image_url: "https://ik.imgkit.net/ikmedia/logo/light_T4buIzohVH.svg",
          category: "category",
          subject: "subject",
          enrolled: 11,
          started_at: new Date(),
          ended_at: curDate,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          user_id: "G42NJ4jlvRNdHbi0b5ROE",
          title: "Go Go Go",
          description: "description",
          image_url: "https://ik.imgkit.net/ikmedia/logo/light_T4buIzohVH.svg",
          category: "category",
          subject: "subject",
          enrolled: 10,
          started_at: new Date(),
          ended_at: curDate,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          user_id: "G42NJ4jlvRNdHbi0b5ROE",
          title: "โอเค เบตง",
          description: "description",
          image_url: "https://ik.imgkit.net/ikmedia/logo/light_T4buIzohVH.svg",
          category: "category",
          subject: "subject",
          enrolled: 9,
          started_at: new Date(),
          ended_at: curDate,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          user_id: "G42NJ4jlvRNdHbi0b5ROE",
          title: "12 น้อยไปนิด",
          description: "description",
          image_url: "https://ik.imgkit.net/ikmedia/logo/light_T4buIzohVH.svg",
          category: "category",
          subject: "subject",
          enrolled: 8,
          started_at: new Date(),
          ended_at: curDate,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          user_id: "G42NJ4jlvRNdHbi0b5ROE",
          title: "55555555555555",
          description: "description",
          image_url: "https://ik.imgkit.net/ikmedia/logo/light_T4buIzohVH.svg",
          category: "category",
          subject: "subject",
          enrolled: 7,
          started_at: new Date(),
          ended_at: curDate,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          user_id: "G42NJ4jlvRNdHbi0b5ROE",
          title: "เทสสสสสสสสสสสส",
          description: "description",
          image_url: "https://ik.imgkit.net/ikmedia/logo/light_T4buIzohVH.svg",
          category: "category",
          subject: "subject",
          enrolled: 6,
          started_at: new Date(),
          ended_at: curDate,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          user_id: "G42NJ4jlvRNdHbi0b5ROE",
          title: "Super Testttttttttt",
          description: "description",
          image_url: "https://ik.imgkit.net/ikmedia/logo/light_T4buIzohVH.svg",
          category: "category",
          subject: "subject",
          enrolled: 5,
          started_at: new Date(),
          ended_at: curDate,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          user_id: "G42NJ4jlvRNdHbi0b5ROE",
          title: "Yes sir!",
          description: "description",
          image_url: "https://ik.imgkit.net/ikmedia/logo/light_T4buIzohVH.svg",
          category: "category",
          subject: "subject",
          enrolled: 4,
          started_at: new Date(),
          ended_at: curDate,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          user_id: "G42NJ4jlvRNdHbi0b5ROE",
          title: "!@@#%$#%^#&",
          description: "description",
          image_url: "https://ik.imgkit.net/ikmedia/logo/light_T4buIzohVH.svg",
          category: "category",
          subject: "subject",
          enrolled: 3,
          started_at: new Date(),
          ended_at: curDate,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          user_id: "G42NJ4jlvRNdHbi0b5ROE",
          title: "Monday Tuesday Wednesday",
          description: "description",
          image_url: "https://ik.imgkit.net/ikmedia/logo/light_T4buIzohVH.svg",
          category: "category",
          subject: "subject",
          enrolled: 2,
          started_at: new Date(),
          ended_at: curDate,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          user_id: "G42NJ4jlvRNdHbi0b5ROE",
          title: "Seven day a week",
          description: "description",
          image_url: "https://ik.imgkit.net/ikmedia/logo/light_T4buIzohVH.svg",
          category: "category",
          subject: "subject",
          enrolled: 1,
          started_at: new Date(),
          ended_at: curDate,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          user_id: "G42NJ4jlvRNdHbi0b5ROE",
          title: "Love Love",
          description: "description",
          image_url: "https://ik.imgkit.net/ikmedia/logo/light_T4buIzohVH.svg",
          category: "category",
          subject: "subject",
          enrolled: 1,
          started_at: new Date(),
          ended_at: curDate,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          user_id: "G42NJ4jlvRNdHbi0b5ROE",
          title: "Hate Hate",
          description: "description",
          image_url: "https://ik.imgkit.net/ikmedia/logo/light_T4buIzohVH.svg",
          category: "category",
          subject: "subject",
          enrolled: 2,
          started_at: new Date(),
          ended_at: curDate,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          user_id: "G42NJ4jlvRNdHbi0b5ROE",
          title: "Something random",
          description: "description",
          image_url: "https://ik.imgkit.net/ikmedia/logo/light_T4buIzohVH.svg",
          category: "category",
          subject: "subject",
          enrolled: 3,
          started_at: new Date(),
          ended_at: curDate,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          user_id: "G42NJ4jlvRNdHbi0b5ROE",
          title: "Modern Javascript",
          description: "description",
          image_url: "https://ik.imgkit.net/ikmedia/logo/light_T4buIzohVH.svg",
          category: "category",
          subject: "subject",
          enrolled: 4,
          started_at: new Date(),
          ended_at: curDate,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          user_id: "G42NJ4jlvRNdHbi0b5ROE",
          title: "Hello World!",
          description: "description",
          image_url: "https://ik.imgkit.net/ikmedia/logo/light_T4buIzohVH.svg",
          category: "category",
          subject: "subject",
          enrolled: 5,
          started_at: new Date(),
          ended_at: curDate,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          user_id: "G42NJ4jlvRNdHbi0b5ROE",
          title: "Something not-random",
          description: "description",
          image_url: "https://ik.imgkit.net/ikmedia/logo/light_T4buIzohVH.svg",
          category: "category",
          subject: "subject",
          enrolled: 6,
          started_at: new Date(),
          ended_at: curDate,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          user_id: "G42NJ4jlvRNdHbi0b5ROE",
          title: "Something went wrong",
          description: "description",
          image_url: "https://ik.imgkit.net/ikmedia/logo/light_T4buIzohVH.svg",
          category: "category",
          subject: "subject",
          enrolled: 7,
          started_at: new Date(),
          ended_at: curDate,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          user_id: "G42NJ4jlvRNdHbi0b5ROE",
          title: "Something went gone",
          description: "description",
          image_url: "https://ik.imgkit.net/ikmedia/logo/light_T4buIzohVH.svg",
          category: "category",
          subject: "subject",
          enrolled: 8,
          started_at: new Date(),
          ended_at: curDate,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          user_id: "G42NJ4jlvRNdHbi0b5ROE",
          title: "Something Something",
          description: "description",
          image_url: "https://ik.imgkit.net/ikmedia/logo/light_T4buIzohVH.svg",
          category: "category",
          subject: "subject",
          enrolled: 9,
          started_at: new Date(),
          ended_at: curDate,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          user_id: "G42NJ4jlvRNdHbi0b5ROE",
          title: "Something XD",
          description: "description",
          image_url: "https://ik.imgkit.net/ikmedia/logo/light_T4buIzohVH.svg",
          category: "category",
          subject: "subject",
          enrolled: 10,
          started_at: new Date(),
          ended_at: curDate,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          user_id: "G42NJ4jlvRNdHbi0b5ROE",
          title: "Something changing",
          description: "description",
          image_url: "https://ik.imgkit.net/ikmedia/logo/light_T4buIzohVH.svg",
          category: "category",
          subject: "subject",
          enrolled: 11,
          started_at: new Date(),
          ended_at: curDate,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          user_id: "G42NJ4jlvRNdHbi0b5ROE",
          title: "Sometimes",
          description: "description",
          image_url: "https://ik.imgkit.net/ikmedia/logo/light_T4buIzohVH.svg",
          category: "category",
          subject: "subject",
          enrolled: 12,
          started_at: new Date(),
          ended_at: curDate,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          user_id: "G42NJ4jlvRNdHbi0b5ROE",
          title: "So-me-ti-mes",
          description: "description",
          image_url: "https://ik.imgkit.net/ikmedia/logo/light_T4buIzohVH.svg",
          category: "category",
          subject: "subject",
          enrolled: 13,
          started_at: new Date(),
          ended_at: curDate,
          created_at: new Date(),
          updated_at: new Date(),
        },
      ],
      {}
    );
  },

  async down(queryInterface, Sequelize) {
    /**
     * Add commands to revert seed here.
     *
     * Example:
     * await queryInterface.bulkDelete('People', null, {});
     */

    await queryInterface.bulkDelete("course", null, {});
    await queryInterface.bulkDelete("customer_info", null, {});
    await queryInterface.bulkDelete("authentication", null, {});
    await queryInterface.bulkDelete("role", null, {});
  },
};
